export const MOCK_JIRA_TASKS = [
  {
    id: "OPS-1001",
    title: "Check Production Database Connection Issues",
    status: "To Do",
    assignee: "Alice",
    priority: "High",
    dueDate: "2024-04-10",
    labels: ["database", "critical"],
    description: "Monitoring shows frequent connection timeouts. Need to verify connection pool configuration.",
  },
  {
    id: "OPS-1002",
    title: "Upgrade Kubernetes Cluster to v1.28",
    status: "In Progress",
    assignee: "Bob",
    priority: "Medium",
    dueDate: "2024-04-15",
    labels: ["infra", "k8s"],
    description: "Ensure cluster security and feature updates. Verify in staging before production rollout.",
  },
  {
    id: "OPS-1003",
    title: "Fix Web Server Memory Leak",
    status: "Done",
    assignee: "Alice",
    priority: "High",
    dueDate: "2024-03-25",
    labels: ["bug", "backend"],
    description: "Resolved memory leak caused by improper Express middleware usage.",
  },
  {
    id: "OPS-1004",
    title: "Renew SSL Certificates",
    status: "To Do",
    assignee: "Charlie",
    priority: "High",
    dueDate: "2024-04-01",
    labels: ["security", "ops"],
    description: "Domain certificates expire soon. Need to re-issue before manual expiration deadline.",
  },
  {
    id: "OPS-1005",
    title: "Optimize Frontend Caching Strategy",
    status: "In Progress",
    assignee: "David",
    priority: "Low",
    dueDate: "2024-04-20",
    labels: ["performance", "frontend"],
    description: "Improve first paint speeds using Cloudflare and Service Workers.",
  },
  {
    id: "OPS-1006",
    title: "Implement CI/CD Automation Scripts",
    status: "To Do",
    assignee: "Charlie",
    priority: "Medium",
    dueDate: "2024-05-01",
    labels: ["devops", "github-actions"],
    description: "Replace legacy manual deployment process with GitHub Actions.",
  },
  {
    id: "OPS-1007",
    title: "Clean Up Expired Log Files",
    status: "To Do",
    assignee: "Alice",
    priority: "Low",
    dueDate: "2024-04-12",
    labels: ["maintenance", "system"],
    description: "Logs are filling up disk space. Remove all log files older than 30 days.",
  },
  {
    id: "OPS-1008",
    title: "Annual Security Audit Planning",
    status: "To Do",
    assignee: "Bob",
    priority: "Medium",
    dueDate: "2024-12-31",
    labels: ["compliance", "security"],
    description: "Prepare penetration tests for production environments and write compliance reports.",
  },
];
